FROM python:3.12-slim

WORKDIR /travelagency

COPY requirement.txt .

RUN pip  install --no-cache-dir -r requirement.txt

COPY . .

EXPOSE 8000

CMD ["python","manage.py","runserver","0.0.0.0:8000"]

